# Generated by Django 3.2 on 2021-07-14 06:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_title', models.CharField(max_length=100)),
                ('game_availbility', models.BooleanField(default=True)),
                ('game_description', models.TextField(blank=True)),
                ('game_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('release_date', models.DateField(default=datetime.date)),
                ('genre', models.CharField(default='test', max_length=50)),
                ('publisher', models.CharField(default='test', max_length=50)),
                ('rating', models.CharField(default='test', max_length=50)),
                ('hdd', models.CharField(default='test', max_length=50)),
                ('compatibility', models.CharField(default='test', max_length=50)),
                ('photo_main', models.ImageField(default='default.jpg', upload_to='photos/%Y/%m/%d/')),
                ('photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_5', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
            ],
        ),
    ]
