# Generated by Django 3.2 on 2021-07-14 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='release_date',
            field=models.DateField(default='test'),
        ),
    ]
