# Generated by Django 3.2 on 2021-07-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_listing_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='hdd',
            field=models.CharField(blank=True, default='test', max_length=50),
        ),
    ]
